//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniveristyWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestItem
    {
        public int Id { get; set; }
        public int qty { get; set; }
        public string productDesc { get; set; }
        public string productCat { get; set; }
        public int ProductId { get; set; }
        public int EmployeeId { get; set; }
        public int RequestId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
        public virtual Request Request { get; set; }
    }
}
