//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogue
    {
        public int Id { get; set; }
        public string item_code { get; set; }
        public string catagory { get; set; }
        public string description { get; set; }
        public int reorder_level { get; set; }
        public int reorder_qty { get; set; }
        public string unit_of_measure { get; set; }
    }
}
