//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Id { get; set; }
        public string dept_name { get; set; }
        public string contant_name { get; set; }
        public int phone { get; set; }
        public int fax { get; set; }
        public string dept_head { get; set; }
        public string collection_point { get; set; }
        public string representative_name { get; set; }
    }
}
