//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int phone { get; set; }
        public string password { get; set; }
        public int DepartmentId { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.Guid> sessionId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
    }
}
