//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDetails
    {
        public int Id { get; set; }
        public System.DateTime createdAt { get; set; }
        public string empName { get; set; }
        public string empNo { get; set; }
        public string empEmail { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public string deptName { get; set; }
        public System.DateTime requestDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
